import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Payment } from '../../payments/entities/payment.entity';
import { Tenant } from '../../tenants/entities/tenant.entity';

/**
 * An invoice document attached to a payment.
 *
 * Invoices are produced by the source platforms - this service does not
 * generate them. It stores the file (or just a reference to it) so the
 * paperwork sits alongside the money.
 *
 * An invoice can be uploaded before a payment exists and attached
 * afterwards, which is why `paymentId` is nullable.
 */
@Entity('invoices')
@Index(['tenantId', 'createdAt'])
export class Invoice {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  tenantId: number;

  @ManyToOne(() => Tenant)
  @JoinColumn({ name: 'tenantId' })
  tenant: Tenant;

  @Column({ nullable: true })
  paymentId?: number;

  @ManyToOne(() => Payment, (payment) => payment.invoices, { nullable: true })
  @JoinColumn({ name: 'paymentId' })
  payment?: Payment;

  /** The platform's own invoice number, e.g. 'INV-2043'. */
  @Column({ nullable: true })
  invoiceNumber?: string;

  /** Filename as the uploader saw it. Never used as a path. */
  @Column({ nullable: true })
  originalFilename?: string;

  @Column({ nullable: true })
  mimeType?: string;

  @Column({ default: 0 })
  sizeBytes: number;

  /**
   * Opaque uuid filename on disk. Generated by us - the client's filename
   * is never trusted for path construction.
   */
  @Column({ nullable: true })
  storageKey?: string;

  /**
   * Alternative to storing the file: a link to the invoice as it already
   * lives in the source platform.
   */
  @Column({ nullable: true })
  externalUrl?: string;

  @Column({ nullable: true })
  uploadedByUserId?: number;

  @CreateDateColumn()
  createdAt: Date;
}
